version: "3"

services:
  backend-svc:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    ports:
      - 8080:5000
    # Make sure to create your .env
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd!
      - MONGO_SERVER=mongo_db
    links:
      - mongo_db
    depends_on:
      - mongo_db
    volumes:
      - ./backend:/app
    restart: always
  frontend-svc:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 8090:3000
    links:
      - backend-svc
    depends_on:
      - backend-svc
  mongo_db:
    image: mongo:latest
    ports:
      - 12345:27017
    # Make sure to create your .env
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd!
      - MONGO_SERVER=mongo_db
    restart: always
    volumes:
      - ./mongo_db:/data/db